### ISSUE TITLE
"0.1.3 All Paths" example in the backtracking chapter

### ISSUE THREAD

**Issue by Zane-XY** [liyin2015/Algorithms-and-Coding-Interviews#5]
Thank you  for the hard work.

I have trouble understanding the "all paths" example in the backtracking chapter.

Unlike the in the permutations and combinations example, the arguments in this function is undocumented, and why the graph can be represented in the array is not explained. 

![image](https://user-images.githubusercontent.com/2939476/57823983-1e7c3100-77cc-11e9-99c3-9f25d81433d0.png)

**Comment by liyin2015** [comment]
Hi, @Zane-XY The way to represent a graph can be found in DATA structure part, you can download the pdf of the whole book [here](https://github.com/liyin2015/Algorithms-and-Coding-Interviews/blob/master/Preparing_for_the_real-world_software_engineering.pdf).
